import type { NextConfig } from "next";
import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

// Capture Twitter env vars at build time.
// Vercel injects env vars at build time but NOT into serverless function runtime.
// Strategy 1: Generate a TS module with hardcoded values
// Strategy 2: Use next.config env property to inline process.env replacements
const twitterClientId = process.env.TWITTER_CLIENT_ID || "";
const twitterClientSecret = process.env.TWITTER_CLIENT_SECRET || "";
const buildTime = new Date().toISOString();

// Encode values so Vercel's post-build processing can't pattern-match
// and strip them from the compiled output (encrypted env var security feature).
const encodedId = Buffer.from(twitterClientId.trim()).toString("base64");
const encodedSecret = Buffer.from(twitterClientSecret.trim()).toString("base64");

const genPath = join(process.cwd(), "src/lib/_twitter-build-config.ts");
writeFileSync(
  genPath,
  `// Auto-generated by next.config.ts at build time — do not edit\n` +
    `const _d = (s: string) => Buffer.from(s, "base64").toString("utf8");\n` +
    `export const TWITTER_CLIENT_ID = _d(${JSON.stringify(encodedId)});\n` +
    `export const TWITTER_CLIENT_SECRET = _d(${JSON.stringify(encodedSecret)});\n` +
    `export const BUILD_TIMESTAMP = ${JSON.stringify(buildTime)};\n`
);

console.log(`[next.config.ts] cwd=${process.cwd()}`);
console.log(`[next.config.ts] Encoded ID: ${encodedId.length} chars, Secret: ${encodedSecret.length} chars`);

const nextConfig: NextConfig = {
  env: {
    // Base64-encode values to prevent Vercel post-build stripping of encrypted env values
    BAKED_TWITTER_CLIENT_ID: encodedId,
    BAKED_TWITTER_CLIENT_SECRET: encodedSecret,
    BAKED_TWITTER_BUILD_TIMESTAMP: buildTime,
  },
};

export default nextConfig;
