import type { NextConfig } from "next";
import { writeFileSync } from "fs";
import { join } from "path";

// Generate twitter-env.generated.ts from build-time environment variables.
// Vercel injects env vars at build time but NOT into serverless function runtime,
// so we capture them into a TypeScript module that gets bundled into server code.
const twitterClientId = process.env.TWITTER_CLIENT_ID || "";
const twitterClientSecret = process.env.TWITTER_CLIENT_SECRET || "";
const buildTime = new Date().toISOString();

writeFileSync(
  join(process.cwd(), "src/lib/_twitter-build-config.ts"),
  `// Auto-generated by next.config.ts at build time — do not edit\n` +
    `export const TWITTER_CLIENT_ID = ${JSON.stringify(twitterClientId)};\n` +
    `export const TWITTER_CLIENT_SECRET = ${JSON.stringify(twitterClientSecret)};\n` +
    `export const BUILD_TIMESTAMP = ${JSON.stringify(buildTime)};\n`
);

console.log(
  `[next.config.ts] Generated _twitter-build-config.ts: ID=${twitterClientId.length} chars, Secret=${twitterClientSecret.length} chars, time=${buildTime}`
);

const nextConfig: NextConfig = {};

export default nextConfig;
