import type { NextConfig } from "next";
import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

// Capture Twitter env vars at build time.
// Vercel injects env vars at build time but NOT into serverless function runtime.
// Strategy 1: Generate a TS module with hardcoded values
// Strategy 2: Use next.config env property to inline process.env replacements
const twitterClientId = process.env.TWITTER_CLIENT_ID || "";
const twitterClientSecret = process.env.TWITTER_CLIENT_SECRET || "";
const buildTime = new Date().toISOString();

const genPath = join(process.cwd(), "src/lib/_twitter-build-config.ts");
writeFileSync(
  genPath,
  `// Auto-generated by next.config.ts at build time — do not edit\n` +
    `export const TWITTER_CLIENT_ID = ${JSON.stringify(twitterClientId)};\n` +
    `export const TWITTER_CLIENT_SECRET = ${JSON.stringify(twitterClientSecret)};\n` +
    `export const BUILD_TIMESTAMP = ${JSON.stringify(buildTime)};\n`
);

// Verify the file was written correctly
const written = readFileSync(genPath, "utf8");
console.log(`[next.config.ts] cwd=${process.cwd()}`);
console.log(`[next.config.ts] Generated file at: ${genPath}`);
console.log(`[next.config.ts] File content (${written.length} bytes):`);
console.log(written);

const nextConfig: NextConfig = {
  env: {
    TWITTER_CLIENT_ID: twitterClientId,
    TWITTER_CLIENT_SECRET: twitterClientSecret,
    TWITTER_BUILD_TIMESTAMP: buildTime,
  },
};

export default nextConfig;
